ln access_code.gif ../captiveportal-access_code.gif
ln action.php ../captiveportal-action.php
ln bottomBackground.jpg ../captiveportal-bottomBackground.jpg
ln btn_submit.gif ../captiveportal-btn_submit.gif
ln captiveportal.html ../captiveportal-captiveportal.html
ln logo_hi.gif ../captiveportal-logo_hi.gif
ln styles.css ../captiveportal-styles.css
ln terms.php ../index.php
ln topBackground.jpg ../captiveportal-topBackground.jpg
ln welcome_login_hi.gif ../captiveportal-welcome_login_hi.gif
